# fly.toml app configuration file generated for douyin-spider on 2026-08-13T10:54:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'douyin-spider'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
